BossBarHealth:
  Decimal: 2
  Self:
    Enabled: true
    Color: RED
    Style: SEGMENTED_20
    Scale: 2.0
    Format:
      # Display format of normal part of boss bar health, the one which shows constantly
      Normal: '%name% %displayname% %hp_int%/%max_int% %hp%/%max%'
      # Display format of boss bar health when self HP changes
      HpLost: '%name% %displayname% %hp_int%/%max_int% %hp%/%max% &7(&c%change%&7)'
      HpGain: '%name% %displayname% %hp_int%/%max_int% %hp%/%max% &7(&a%change%&7)'
      # Duration of lost/gained hp staying on screen, in ticks
      Duration: 40
  Enemy:
    Enabled: true
    Color: GREEN
    Style: SEGMENTED_20
    Scale: 2.0
    # Duration of enemy's boss bar staying on screen, in ticks
    Duration: 40
    # If it is enabled, enemy's boss bar will over self boss bar when active
    Override: false
    Format:
      HpLost: '%e_type% %e_name% %e_displayname%: %e_hp_int%/%e_max_int% %e_hp%/%e_max% &7(&c%e_change%&7)'
      HpGain: '%e_type% %e_name% %e_displayname%: %e_hp_int%/%e_max_int% %e_hp%/%e_max% &7(&a%e_change%&7)'