BossBarHealth:
  # Decimal places of all numbers including current hp, max hp, hp lost/gained
  Decimal: 2
  Self:
    # If it is enabled, it will show your hp at all times
    Enabled: true
    # Color of the boss bar
    # Avaliable options: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    Color: RED
    # Style of the boss bar
    # Avaliable options: SEGMENTED_10, SEGMENTED_12, SEGMENTED_20, SEGMENTED_6, SOLID
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    Style: SEGMENTED_20
    # Scale of the boss bar health display
    # If the option is 2.0, it shows 40/40 when you have full health
    Scale: 1.0
    Format:
      # Display format of normal part of boss bar health, the one which shows constantly
      # Placeholders:
      # %name%            Player's name
      # %displayname%     Player's display name
      # %hp%:             Player's health
      # %max%:            Player's maximum health
      # %hp_int%          Player's health in integer
      # %max_int%:        Player's maximum health in integer
      Normal: '%name% %displayname% %hp_int%/%max_int% %hp%/%max%'
      # Display format of boss bar health when self HP changes
      # Placeholders:
      # %change%          Player's health gained/lost
      HpLost: '%name% %displayname% %hp_int%/%max_int% %hp%/%max% &7(&c%change%&7)'
      HpGain: '%name% %displayname% %hp_int%/%max_int% %hp%/%max% &7(&a%change%&7)'
      # Duration of lost/gained hp staying on screen, in ticks
      Duration: 40
  Enemy:
    # If it is enabled, it will show enemy's hp when you attack
    Enabled: true
    Color: GREEN
    Style: SEGMENTED_20
    Scale: 1.0
    # Duration of enemy's boss bar staying on screen, in ticks
    Duration: 40
    # If it is enabled, enemy's boss bar will override self boss bar when active
    Override: false
    Format:
      # Placeholders:
      # %e_type%          Entity type of the enemy
      # %e_name%          Name of the enemy, only work when the enemy is player
      # %e_displayname%   Name of the enemy, only work when the enemy is player
      # %e_hp%            Enemy's health
      # %e_max%           Enemy's maximum health
      # %e_hp_int%        Enemy's health in integer
      # %e_max_int%       Enemy's maximum health in integer
      HpLost: '%e_type% %e_name% %e_displayname%: %e_hp_int%/%e_max_int% %e_hp%/%e_max% &7(&c%e_change%&7)'
      HpGain: '%e_type% %e_name% %e_displayname%: %e_hp_int%/%e_max_int% %e_hp%/%e_max% &7(&a%e_change%&7)'