main: to.epac.factorycraft.bossbarhealth.BossBarHealth
version: 4.0.0
name: BossBarHealth
author: i998979
description: Display players and enemies health on boss bar
softdepend: [PlaceholderAPI, WorldGuard, WorldGuardEvents]
api-version: 1.13

commands:
  bossbarhealth:
    aliases: [bbh]
    description: Main command
    
permissions:
  BossBarHealth.Admin:
    description: Give access to all commands